# Generated by Django 4.2.11 on 2024-04-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.IntegerField(blank=True),
        ),
    ]
