# Generated by Django 4.2.11 on 2024-04-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
