# Generated by Django 4.2.11 on 2024-04-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=20)),
                ('Product_description', models.CharField(max_length=50)),
                ('product_price', models.FloatField()),
                ('product_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
