# Generated by Django 4.2.11 on 2024-04-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_products_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('query_params', models.JSONField(blank=True, null=True)),
                ('body', models.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['id']},
        ),
    ]
