# Generated by Django 4.2.11 on 2024-04-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_body_apilog_response_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilog',
            name='response_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
