# Generated by Django 4.2.11 on 2024-04-09 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cart_cartitem_cart_products_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
